#! /bin/sh -e
### BEGIN INIT INFO
# Provides:          mpd-myfm
# Required-Start:    mpd
# Required-Stop:     mpd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the mpd-myfm mpd-client as a daemon.
# Description:       Make mpd (music player daemon) into your own
#                    personalised radio station.
### END INIT INFO

PIDFILE=$(grep "^pidfile" /etc/mpd-myfm.conf |awk -F\= '{print $2}')
if [ -z $PIDFILE ] ; then
	PIDFILE="/tmp/mpd-myfm.pid"
fi

# Get lsb functions
. /lib/lsb/init-functions
. /etc/default/rcS

case "$1" in
	start)
		if [ -f "$PIDFILE" ] ; then
			if kill -0 `cat "$PIDFILE"` > /dev/null 2>&1 ; then
				log_begin_msg "pidfile exists, mpd-myfm client probably already running. If you know it is not remove $PIDFILE"
				log_end_msg 1
				exit 1
			fi
			log_begin_msg "reusing stale pidfile at $PIDFILE"
		fi
		log_begin_msg "Starting mpd-myfm services..."
		start-stop-daemon --start --exec /usr/local/bin/mpd-myfm -- -D -F $PIDFILE 
		log_end_msg $?
		;;
	stop)
		log_begin_msg "Stopping mpd-myfm services..."
		start-stop-daemon --stop --pidfile $PIDFILE --retry 4
		log_end_msg $?
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	reload|force-reload) 
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		status_of_proc /usr/local/bin/mpd-myfm && exit 0 || exit $?
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|reload|force-reload|status}"
		exit 1
esac

exit 0
